backend:
  name: github
  repo: brunetto/biemmezeta.github.io
  branch: main

  base_url: https://decap-cms-oauth.netlify.app
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Services"
    folder: "pages"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Configuration"
        name: "site"
        file: "_data/site.json"

        fields:
          - { label: "Owner", name: "owner", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
